In [1]:
import numpy as np

In [2]:
array_1 = np.array([[0, 1], [10, 11], [20, 21]], float)
array_1

array([[  0.,   1.],
       [ 10.,  11.],
       [ 20.,  21.]])

In [4]:
a_list = [0, 1, 10, 11, 20, 21]
vector = np.array(a_list, float)
vector

array([  0.,   1.,  10.,  11.,  20.,  21.])

In [6]:
array_2 = np.array(a_list, float).reshape((3,2))
array_2

array([[  0.,   1.],
       [ 10.,  11.],
       [ 20.,  21.]])

In [7]:
array_2 * 4

array([[  0.,   4.],
       [ 40.,  44.],
       [ 80.,  84.]])

In [8]:
array_2 * array_2

array([[   0.,    1.],
       [ 100.,  121.],
       [ 400.,  441.]])

In [9]:
vector[0]

0.0

In [10]:
vector[::-1]

array([ 21.,  20.,  11.,  10.,   1.,   0.])

In [11]:
array_3_list = np.array([0, 1, 2, 20, 11, 12, 20, 21, 22], float)
array_3_list

array([  0.,   1.,   2.,  20.,  11.,  12.,  20.,  21.,  22.])

In [12]:
array_3 = array_3_list.reshape(3, 3)

In [13]:
array_3

array([[  0.,   1.,   2.],
       [ 20.,  11.,  12.],
       [ 20.,  21.,  22.]])

In [14]:
array_3[0]

array([ 0.,  1.,  2.])

In [15]:
array_3[-1]

array([ 20.,  21.,  22.])

In [16]:
array_3[0:2]

array([[  0.,   1.,   2.],
       [ 20.,  11.,  12.]])

In [17]:
array_3[2,1]

21.0

In [18]:
array_3[2]

array([ 20.,  21.,  22.])

In [19]:
array_3[:,1]

array([  1.,  11.,  21.])

In [21]:
array_3[..., 1]

array([  1.,  11.,  21.])

In [22]:
array_4 = np.array(range(120), int).reshape(2, 3, 4, 5)
array_4

array([[[[  0,   1,   2,   3,   4],
         [  5,   6,   7,   8,   9],
         [ 10,  11,  12,  13,  14],
         [ 15,  16,  17,  18,  19]],

        [[ 20,  21,  22,  23,  24],
         [ 25,  26,  27,  28,  29],
         [ 30,  31,  32,  33,  34],
         [ 35,  36,  37,  38,  39]],

        [[ 40,  41,  42,  43,  44],
         [ 45,  46,  47,  48,  49],
         [ 50,  51,  52,  53,  54],
         [ 55,  56,  57,  58,  59]]],


       [[[ 60,  61,  62,  63,  64],
         [ 65,  66,  67,  68,  69],
         [ 70,  71,  72,  73,  74],
         [ 75,  76,  77,  78,  79]],

        [[ 80,  81,  82,  83,  84],
         [ 85,  86,  87,  88,  89],
         [ 90,  91,  92,  93,  94],
         [ 95,  96,  97,  98,  99]],

        [[100, 101, 102, 103, 104],
         [105, 106, 107, 108, 109],
         [110, 111, 112, 113, 114],
         [115, 116, 117, 118, 119]]]])

In [23]:
array_4[0, 1]

array([[20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [24]:
array_4[0, 1, 2]

array([30, 31, 32, 33, 34])

In [26]:
array_4[0,..., 1]

array([[ 1,  6, 11, 16],
       [21, 26, 31, 36],
       [41, 46, 51, 56]])

In [27]:
np.array([array_4[0, i, j, 1] for i in range(3) for j in range(4)]).reshape(3, 4)

array([[ 1,  6, 11, 16],
       [21, 26, 31, 36],
       [41, 46, 51, 56]])

In [29]:
arr = np.array([0, 1, 10, 11, 20,21], float).reshape(3,2)
arr

array([[  0.,   1.],
       [ 10.,  11.],
       [ 20.,  21.]])

In [30]:
arr.transpose()

array([[  0.,  10.,  20.],
       [  1.,  11.,  21.]])

In [31]:
print "mean: ", arr.mean()
print "min: ", arr.min()
print "max: ", arr.max()
print "sum: ", arr.sum()
print "std: ", arr.std()

mean:  10.5
min:  0.0
max:  21.0
sum:  63.0
std:  8.18026079454


In [32]:
import numpy as np
pi = np.pi

print("pi:", pi)
print()

#... these include the following (and many other common functions):
print("log:     " , np.log(pi))
print("sqrt:    " , np.sqrt(pi))
print("sin:     " , np.sin(pi))
print("cos:     " , np.cos(pi))
print("tan:     " , np.cos(pi) )
print("arcsin:  " , np.arcsin(.1))
print("arctanh: " , np.arctanh(.1))

('pi:', 3.141592653589793)
()
('log:     ', 1.1447298858494002)
('sqrt:    ', 1.7724538509055159)
('sin:     ', 1.2246467991473532e-16)
('cos:     ', -1.0)
('tan:     ', -1.0)
('arcsin:  ', 0.1001674211615598)
('arctanh: ', 0.10033534773107558)


In [33]:
arr

array([[  0.,   1.],
       [ 10.,  11.],
       [ 20.,  21.]])

In [34]:
arr_ones = np.ones_like(arr)
arr_ones

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [35]:
arr+arr_ones

array([[  1.,   2.],
       [ 11.,  12.],
       [ 21.,  22.]])

In [36]:
arr_onezero = arr %2
arr_onezero

array([[ 0.,  1.],
       [ 0.,  1.],
       [ 0.,  1.]])

In [37]:
arr * arr_onezero

array([[  0.,   1.],
       [  0.,  11.],
       [  0.,  21.]])

In [39]:
a = np.array([[1., 2.], [3., 4.]])
a_dash = np.linalg.inv(a)
a_dash

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [40]:
np.linalg.det(a)

-2.0000000000000004

In [41]:
np.dot(a, a_dash)

array([[  1.00000000e+00,   1.11022302e-16],
       [  0.00000000e+00,   1.00000000e+00]])

In [42]:
e_vals, e_vecs = np.linalg.eig(a)
e_vals, e_vecs 

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [43]:
selector = a > 1

In [44]:
selector

array([[False,  True],
       [ True,  True]], dtype=bool)

In [45]:
a[selector]

array([ 2.,  3.,  4.])

In [46]:
a[[1, 0]]

array([[ 3.,  4.],
       [ 1.,  2.]])

In [47]:
a[[(0,1), (1,0)]]

array([ 2.,  3.])